// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("osqueryreceiver")
	ScopeName = "github.com/newrelic/nrdot-collector-components/receiver/osqueryreceiver"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
