// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for oracledb metrics.
type MetricsConfig struct {
	OracledbAsmDiskgroupFreeMb                                 MetricConfig `mapstructure:"oracledb.asm.diskgroup.free_mb"`
	OracledbAsmDiskgroupOfflineDisks                           MetricConfig `mapstructure:"oracledb.asm.diskgroup.offline_disks"`
	OracledbAsmDiskgroupTotalMb                                MetricConfig `mapstructure:"oracledb.asm.diskgroup.total_mb"`
	OracledbChildCursorsBufferGets                             MetricConfig `mapstructure:"oracledb.child_cursors.buffer_gets"`
	OracledbChildCursorsCPUTime                                MetricConfig `mapstructure:"oracledb.child_cursors.cpu_time"`
	OracledbChildCursorsDetails                                MetricConfig `mapstructure:"oracledb.child_cursors.details"`
	OracledbChildCursorsDiskReads                              MetricConfig `mapstructure:"oracledb.child_cursors.disk_reads"`
	OracledbChildCursorsElapsedTime                            MetricConfig `mapstructure:"oracledb.child_cursors.elapsed_time"`
	OracledbChildCursorsExecutions                             MetricConfig `mapstructure:"oracledb.child_cursors.executions"`
	OracledbChildCursorsInvalidations                          MetricConfig `mapstructure:"oracledb.child_cursors.invalidations"`
	OracledbChildCursorsUserIoWaitTime                         MetricConfig `mapstructure:"oracledb.child_cursors.user_io_wait_time"`
	OracledbConnectionActiveSessions                           MetricConfig `mapstructure:"oracledb.connection.active_sessions"`
	OracledbConnectionBytesReceived                            MetricConfig `mapstructure:"oracledb.connection.bytes_received"`
	OracledbConnectionBytesSent                                MetricConfig `mapstructure:"oracledb.connection.bytes_sent"`
	OracledbConnectionCircuits                                 MetricConfig `mapstructure:"oracledb.connection.circuits"`
	OracledbConnectionDispatchers                              MetricConfig `mapstructure:"oracledb.connection.dispatchers"`
	OracledbConnectionExecuteCount                             MetricConfig `mapstructure:"oracledb.connection.execute_count"`
	OracledbConnectionInactiveSessions                         MetricConfig `mapstructure:"oracledb.connection.inactive_sessions"`
	OracledbConnectionLogonsCumulative                         MetricConfig `mapstructure:"oracledb.connection.logons_cumulative"`
	OracledbConnectionLogonsCurrent                            MetricConfig `mapstructure:"oracledb.connection.logons_current"`
	OracledbConnectionParseCountHard                           MetricConfig `mapstructure:"oracledb.connection.parse_count_hard"`
	OracledbConnectionParseCountTotal                          MetricConfig `mapstructure:"oracledb.connection.parse_count_total"`
	OracledbConnectionResourceCurrentUtilization               MetricConfig `mapstructure:"oracledb.connection.resource_current_utilization"`
	OracledbConnectionResourceLimit                            MetricConfig `mapstructure:"oracledb.connection.resource_limit"`
	OracledbConnectionResourceMaxUtilization                   MetricConfig `mapstructure:"oracledb.connection.resource_max_utilization"`
	OracledbConnectionSessionsByStatus                         MetricConfig `mapstructure:"oracledb.connection.sessions_by_status"`
	OracledbConnectionSessionsByType                           MetricConfig `mapstructure:"oracledb.connection.sessions_by_type"`
	OracledbConnectionSharedServers                            MetricConfig `mapstructure:"oracledb.connection.shared_servers"`
	OracledbConnectionSqlnetRoundtrips                         MetricConfig `mapstructure:"oracledb.connection.sqlnet_roundtrips"`
	OracledbConnectionTotalSessions                            MetricConfig `mapstructure:"oracledb.connection.total_sessions"`
	OracledbConnectionUserCommits                              MetricConfig `mapstructure:"oracledb.connection.user_commits"`
	OracledbConnectionUserRollbacks                            MetricConfig `mapstructure:"oracledb.connection.user_rollbacks"`
	OracledbContainerRestricted                                MetricConfig `mapstructure:"oracledb.container.restricted"`
	OracledbContainerStatus                                    MetricConfig `mapstructure:"oracledb.container.status"`
	OracledbDatabaseInfo                                       MetricConfig `mapstructure:"oracledb.database.info"`
	OracledbDatabaseRole                                       MetricConfig `mapstructure:"oracledb.database.role"`
	OracledbDatafileAutoextensible                             MetricConfig `mapstructure:"oracledb.datafile.autoextensible"`
	OracledbDatafileSizeBytes                                  MetricConfig `mapstructure:"oracledb.datafile.size_bytes"`
	OracledbDatafileUsedBytes                                  MetricConfig `mapstructure:"oracledb.datafile.used_bytes"`
	OracledbDbID                                               MetricConfig `mapstructure:"oracledb.db_id"`
	OracledbDiskBlocksRead                                     MetricConfig `mapstructure:"oracledb.disk.blocks_read"`
	OracledbDiskBlocksWritten                                  MetricConfig `mapstructure:"oracledb.disk.blocks_written"`
	OracledbDiskReadTimeMilliseconds                           MetricConfig `mapstructure:"oracledb.disk.read_time_milliseconds"`
	OracledbDiskReads                                          MetricConfig `mapstructure:"oracledb.disk.reads"`
	OracledbDiskWriteTimeMilliseconds                          MetricConfig `mapstructure:"oracledb.disk.write_time_milliseconds"`
	OracledbDiskWrites                                         MetricConfig `mapstructure:"oracledb.disk.writes"`
	OracledbExecutionPlan                                      MetricConfig `mapstructure:"oracledb.execution_plan"`
	OracledbGlobalName                                         MetricConfig `mapstructure:"oracledb.global_name"`
	OracledbHostingInfo                                        MetricConfig `mapstructure:"oracledb.hosting.info"`
	OracledbLockedAccounts                                     MetricConfig `mapstructure:"oracledb.locked_accounts"`
	OracledbLongRunningQueries                                 MetricConfig `mapstructure:"oracledb.long_running_queries"`
	OracledbMemoryPgaAllocatedBytes                            MetricConfig `mapstructure:"oracledb.memory.pga_allocated_bytes"`
	OracledbMemoryPgaFreeableBytes                             MetricConfig `mapstructure:"oracledb.memory.pga_freeable_bytes"`
	OracledbMemoryPgaInUseBytes                                MetricConfig `mapstructure:"oracledb.memory.pga_in_use_bytes"`
	OracledbMemoryPgaMaxSizeBytes                              MetricConfig `mapstructure:"oracledb.memory.pga_max_size_bytes"`
	OracledbMemorySgaSharedPoolLibraryCacheSharableBytes       MetricConfig `mapstructure:"oracledb.memory.sga_shared_pool_library_cache_sharable_bytes"`
	OracledbMemorySgaSharedPoolLibraryCacheUserBytes           MetricConfig `mapstructure:"oracledb.memory.sga_shared_pool_library_cache_user_bytes"`
	OracledbMemorySgaUgaTotalBytes                             MetricConfig `mapstructure:"oracledb.memory.sga_uga_total_bytes"`
	OracledbPdbActiveParallelSessions                          MetricConfig `mapstructure:"oracledb.pdb.active_parallel_sessions"`
	OracledbPdbActiveSerialSessions                            MetricConfig `mapstructure:"oracledb.pdb.active_serial_sessions"`
	OracledbPdbAverageActiveSessions                           MetricConfig `mapstructure:"oracledb.pdb.average_active_sessions"`
	OracledbPdbBackgroundCPUUsagePerSecond                     MetricConfig `mapstructure:"oracledb.pdb.background_cpu_usage_per_second"`
	OracledbPdbBackgroundTimePerSecond                         MetricConfig `mapstructure:"oracledb.pdb.background_time_per_second"`
	OracledbPdbBlockChangesPerSecond                           MetricConfig `mapstructure:"oracledb.pdb.block_changes_per_second"`
	OracledbPdbBlockChangesPerTransaction                      MetricConfig `mapstructure:"oracledb.pdb.block_changes_per_transaction"`
	OracledbPdbCPUTimeRatio                                    MetricConfig `mapstructure:"oracledb.pdb.cpu_time_ratio"`
	OracledbPdbCPUUsagePerSecond                               MetricConfig `mapstructure:"oracledb.pdb.cpu_usage_per_second"`
	OracledbPdbCPUUsagePerTransaction                          MetricConfig `mapstructure:"oracledb.pdb.cpu_usage_per_transaction"`
	OracledbPdbCurrentLogons                                   MetricConfig `mapstructure:"oracledb.pdb.current_logons"`
	OracledbPdbCurrentOpenCursors                              MetricConfig `mapstructure:"oracledb.pdb.current_open_cursors"`
	OracledbPdbDbPhysicalReadBytesPerSecond                    MetricConfig `mapstructure:"oracledb.pdb.db_physical_read_bytes_per_second"`
	OracledbPdbDbPhysicalReadsPerSecond                        MetricConfig `mapstructure:"oracledb.pdb.db_physical_reads_per_second"`
	OracledbPdbDbPhysicalWriteBytesPerSecond                   MetricConfig `mapstructure:"oracledb.pdb.db_physical_write_bytes_per_second"`
	OracledbPdbDbPhysicalWritesPerSecond                       MetricConfig `mapstructure:"oracledb.pdb.db_physical_writes_per_second"`
	OracledbPdbExecuteWithoutParseRatio                        MetricConfig `mapstructure:"oracledb.pdb.execute_without_parse_ratio"`
	OracledbPdbExecutionsPerSecond                             MetricConfig `mapstructure:"oracledb.pdb.executions_per_second"`
	OracledbPdbExecutionsPerTransaction                        MetricConfig `mapstructure:"oracledb.pdb.executions_per_transaction"`
	OracledbPdbHardParseCountPerSecond                         MetricConfig `mapstructure:"oracledb.pdb.hard_parse_count_per_second"`
	OracledbPdbHardParseCountPerTransaction                    MetricConfig `mapstructure:"oracledb.pdb.hard_parse_count_per_transaction"`
	OracledbPdbLogicalReadsPerSecond                           MetricConfig `mapstructure:"oracledb.pdb.logical_reads_per_second"`
	OracledbPdbLogicalReadsPerTransaction                      MetricConfig `mapstructure:"oracledb.pdb.logical_reads_per_transaction"`
	OracledbPdbLogonsPerSecond                                 MetricConfig `mapstructure:"oracledb.pdb.logons_per_second"`
	OracledbPdbLogonsPerTransaction                            MetricConfig `mapstructure:"oracledb.pdb.logons_per_transaction"`
	OracledbPdbNetworkTrafficBytePerSecond                     MetricConfig `mapstructure:"oracledb.pdb.network_traffic_byte_per_second"`
	OracledbPdbOpenCursorsPerSecond                            MetricConfig `mapstructure:"oracledb.pdb.open_cursors_per_second"`
	OracledbPdbOpenCursorsPerTransaction                       MetricConfig `mapstructure:"oracledb.pdb.open_cursors_per_transaction"`
	OracledbPdbOpenMode                                        MetricConfig `mapstructure:"oracledb.pdb.open_mode"`
	OracledbPdbParseFailureCountPerSecond                      MetricConfig `mapstructure:"oracledb.pdb.parse_failure_count_per_second"`
	OracledbPdbPhysicalReadBytesPerSecond                      MetricConfig `mapstructure:"oracledb.pdb.physical_read_bytes_per_second"`
	OracledbPdbPhysicalReadsPerTransaction                     MetricConfig `mapstructure:"oracledb.pdb.physical_reads_per_transaction"`
	OracledbPdbPhysicalWriteBytesPerSecond                     MetricConfig `mapstructure:"oracledb.pdb.physical_write_bytes_per_second"`
	OracledbPdbPhysicalWritesPerTransaction                    MetricConfig `mapstructure:"oracledb.pdb.physical_writes_per_transaction"`
	OracledbPdbRedoGeneratedBytesPerSecond                     MetricConfig `mapstructure:"oracledb.pdb.redo_generated_bytes_per_second"`
	OracledbPdbRedoGeneratedBytesPerTransaction                MetricConfig `mapstructure:"oracledb.pdb.redo_generated_bytes_per_transaction"`
	OracledbPdbResponseTimePerTransaction                      MetricConfig `mapstructure:"oracledb.pdb.response_time_per_transaction"`
	OracledbPdbSessionCount                                    MetricConfig `mapstructure:"oracledb.pdb.session_count"`
	OracledbPdbSoftParseRatio                                  MetricConfig `mapstructure:"oracledb.pdb.soft_parse_ratio"`
	OracledbPdbSQLServiceResponseTime                          MetricConfig `mapstructure:"oracledb.pdb.sql_service_response_time"`
	OracledbPdbTotalParseCountPerSecond                        MetricConfig `mapstructure:"oracledb.pdb.total_parse_count_per_second"`
	OracledbPdbTotalParseCountPerTransaction                   MetricConfig `mapstructure:"oracledb.pdb.total_parse_count_per_transaction"`
	OracledbPdbTotalSizeBytes                                  MetricConfig `mapstructure:"oracledb.pdb.total_size_bytes"`
	OracledbPdbTransactionsPerSecond                           MetricConfig `mapstructure:"oracledb.pdb.transactions_per_second"`
	OracledbPdbUserCallsPerSecond                              MetricConfig `mapstructure:"oracledb.pdb.user_calls_per_second"`
	OracledbPdbUserCallsPerTransaction                         MetricConfig `mapstructure:"oracledb.pdb.user_calls_per_transaction"`
	OracledbPdbUserCommitsPerSecond                            MetricConfig `mapstructure:"oracledb.pdb.user_commits_per_second"`
	OracledbPdbUserCommitsPercentage                           MetricConfig `mapstructure:"oracledb.pdb.user_commits_percentage"`
	OracledbPdbUserRollbacksPerSecond                          MetricConfig `mapstructure:"oracledb.pdb.user_rollbacks_per_second"`
	OracledbPdbUserRollbacksPercentage                         MetricConfig `mapstructure:"oracledb.pdb.user_rollbacks_percentage"`
	OracledbPdbWaitTimeRatio                                   MetricConfig `mapstructure:"oracledb.pdb.wait_time_ratio"`
	OracledbRacInstanceActiveState                             MetricConfig `mapstructure:"oracledb.rac.instance.active_state"`
	OracledbRacInstanceArchiverStarted                         MetricConfig `mapstructure:"oracledb.rac.instance.archiver_started"`
	OracledbRacInstanceDatabaseStatus                          MetricConfig `mapstructure:"oracledb.rac.instance.database_status"`
	OracledbRacInstanceLoginsAllowed                           MetricConfig `mapstructure:"oracledb.rac.instance.logins_allowed"`
	OracledbRacInstanceStatus                                  MetricConfig `mapstructure:"oracledb.rac.instance.status"`
	OracledbRacInstanceUptimeSeconds                           MetricConfig `mapstructure:"oracledb.rac.instance.uptime_seconds"`
	OracledbRacInstanceVersionInfo                             MetricConfig `mapstructure:"oracledb.rac.instance.version_info"`
	OracledbRacServiceBlockedStatus                            MetricConfig `mapstructure:"oracledb.rac.service.blocked_status"`
	OracledbRacServiceClbConfig                                MetricConfig `mapstructure:"oracledb.rac.service.clb_config"`
	OracledbRacServiceDrainTimeoutSeconds                      MetricConfig `mapstructure:"oracledb.rac.service.drain_timeout_seconds"`
	OracledbRacServiceFanEnabled                               MetricConfig `mapstructure:"oracledb.rac.service.fan_enabled"`
	OracledbRacServiceGoalConfig                               MetricConfig `mapstructure:"oracledb.rac.service.goal_config"`
	OracledbRacServiceInstanceID                               MetricConfig `mapstructure:"oracledb.rac.service.instance_id"`
	OracledbRacServiceNetworkConfig                            MetricConfig `mapstructure:"oracledb.rac.service.network_config"`
	OracledbRacServiceReplayTimeoutSeconds                     MetricConfig `mapstructure:"oracledb.rac.service.replay_timeout_seconds"`
	OracledbRacServiceTransactionGuardEnabled                  MetricConfig `mapstructure:"oracledb.rac.service.transaction_guard_enabled"`
	OracledbRacTotalWaits                                      MetricConfig `mapstructure:"oracledb.rac.total_waits"`
	OracledbRacWaitTime                                        MetricConfig `mapstructure:"oracledb.rac.wait_time"`
	OracledbRedoLogParallelWriteWaits                          MetricConfig `mapstructure:"oracledb.redo_log_parallel_write_waits"`
	OracledbRedoLogSwitchArchivingNeededWaits                  MetricConfig `mapstructure:"oracledb.redo_log_switch_archiving_needed_waits"`
	OracledbRedoLogSwitchCheckpointIncompleteWaits             MetricConfig `mapstructure:"oracledb.redo_log_switch_checkpoint_incomplete_waits"`
	OracledbRedoLogSwitchCompletionWaits                       MetricConfig `mapstructure:"oracledb.redo_log_switch_completion_waits"`
	OracledbRollbackSegmentsGets                               MetricConfig `mapstructure:"oracledb.rollback_segments_gets"`
	OracledbRollbackSegmentsWaitRatio                          MetricConfig `mapstructure:"oracledb.rollback_segments_wait_ratio"`
	OracledbRollbackSegmentsWaits                              MetricConfig `mapstructure:"oracledb.rollback_segments_waits"`
	OracledbServiceCount                                       MetricConfig `mapstructure:"oracledb.service.count"`
	OracledbServiceStatus                                      MetricConfig `mapstructure:"oracledb.service.status"`
	OracledbSessionsCount                                      MetricConfig `mapstructure:"oracledb.sessions.count"`
	OracledbSgaBufferBusyWaits                                 MetricConfig `mapstructure:"oracledb.sga_buffer_busy_waits"`
	OracledbSgaFixedSizeBytes                                  MetricConfig `mapstructure:"oracledb.sga_fixed_size_bytes"`
	OracledbSgaFreeBufferInspectedWaits                        MetricConfig `mapstructure:"oracledb.sga_free_buffer_inspected_waits"`
	OracledbSgaFreeBufferWaits                                 MetricConfig `mapstructure:"oracledb.sga_free_buffer_waits"`
	OracledbSgaHitRatio                                        MetricConfig `mapstructure:"oracledb.sga_hit_ratio"`
	OracledbSgaLogAllocationRetriesRatio                       MetricConfig `mapstructure:"oracledb.sga_log_allocation_retries_ratio"`
	OracledbSgaLogBufferRedoAllocationRetries                  MetricConfig `mapstructure:"oracledb.sga_log_buffer_redo_allocation_retries"`
	OracledbSgaLogBufferRedoEntries                            MetricConfig `mapstructure:"oracledb.sga_log_buffer_redo_entries"`
	OracledbSgaLogBufferSpaceWaits                             MetricConfig `mapstructure:"oracledb.sga_log_buffer_space_waits"`
	OracledbSgaRedoBuffersBytes                                MetricConfig `mapstructure:"oracledb.sga_redo_buffers_bytes"`
	OracledbSgaSharedPoolDictCacheMissRatio                    MetricConfig `mapstructure:"oracledb.sga_shared_pool_dict_cache_miss_ratio"`
	OracledbSgaSharedPoolLibraryCacheHitRatio                  MetricConfig `mapstructure:"oracledb.sga_shared_pool_library_cache_hit_ratio"`
	OracledbSgaSharedPoolLibraryCacheReloadRatio               MetricConfig `mapstructure:"oracledb.sga_shared_pool_library_cache_reload_ratio"`
	OracledbSlowQueriesExecutionCount                          MetricConfig `mapstructure:"oracledb.slow_queries.execution_count"`
	OracledbSlowQueriesIntervalAvgBufferGets                   MetricConfig `mapstructure:"oracledb.slow_queries.interval_avg_buffer_gets"`
	OracledbSlowQueriesIntervalAvgCPUTime                      MetricConfig `mapstructure:"oracledb.slow_queries.interval_avg_cpu_time"`
	OracledbSlowQueriesIntervalAvgDiskReads                    MetricConfig `mapstructure:"oracledb.slow_queries.interval_avg_disk_reads"`
	OracledbSlowQueriesIntervalAvgDiskWrites                   MetricConfig `mapstructure:"oracledb.slow_queries.interval_avg_disk_writes"`
	OracledbSlowQueriesIntervalAvgElapsedTime                  MetricConfig `mapstructure:"oracledb.slow_queries.interval_avg_elapsed_time"`
	OracledbSlowQueriesIntervalAvgRowsProcessed                MetricConfig `mapstructure:"oracledb.slow_queries.interval_avg_rows_processed"`
	OracledbSlowQueriesIntervalAvgWaitTime                     MetricConfig `mapstructure:"oracledb.slow_queries.interval_avg_wait_time"`
	OracledbSlowQueriesIntervalBufferGets                      MetricConfig `mapstructure:"oracledb.slow_queries.interval_buffer_gets"`
	OracledbSlowQueriesIntervalCPUTime                         MetricConfig `mapstructure:"oracledb.slow_queries.interval_cpu_time"`
	OracledbSlowQueriesIntervalDiskReads                       MetricConfig `mapstructure:"oracledb.slow_queries.interval_disk_reads"`
	OracledbSlowQueriesIntervalDiskWrites                      MetricConfig `mapstructure:"oracledb.slow_queries.interval_disk_writes"`
	OracledbSlowQueriesIntervalElapsedTime                     MetricConfig `mapstructure:"oracledb.slow_queries.interval_elapsed_time"`
	OracledbSlowQueriesIntervalExecutionCount                  MetricConfig `mapstructure:"oracledb.slow_queries.interval_execution_count"`
	OracledbSlowQueriesIntervalRowsProcessed                   MetricConfig `mapstructure:"oracledb.slow_queries.interval_rows_processed"`
	OracledbSlowQueriesIntervalWaitTime                        MetricConfig `mapstructure:"oracledb.slow_queries.interval_wait_time"`
	OracledbSlowQueriesQueryDetails                            MetricConfig `mapstructure:"oracledb.slow_queries.query_details"`
	OracledbSlowQueriesTotalCPUTime                            MetricConfig `mapstructure:"oracledb.slow_queries.total_cpu_time"`
	OracledbSlowQueriesTotalDiskReads                          MetricConfig `mapstructure:"oracledb.slow_queries.total_disk_reads"`
	OracledbSlowQueriesTotalDiskWrites                         MetricConfig `mapstructure:"oracledb.slow_queries.total_disk_writes"`
	OracledbSlowQueriesTotalElapsedTime                        MetricConfig `mapstructure:"oracledb.slow_queries.total_elapsed_time"`
	OracledbSlowQueriesTotalRowsExamined                       MetricConfig `mapstructure:"oracledb.slow_queries.total_rows_examined"`
	OracledbSlowQueriesTotalRowsReturned                       MetricConfig `mapstructure:"oracledb.slow_queries.total_rows_returned"`
	OracledbSlowQueriesTotalWaitTime                           MetricConfig `mapstructure:"oracledb.slow_queries.total_wait_time"`
	OracledbSortsDisk                                          MetricConfig `mapstructure:"oracledb.sorts_disk"`
	OracledbSortsMemory                                        MetricConfig `mapstructure:"oracledb.sorts_memory"`
	OracledbSystemActiveParallelSessions                       MetricConfig `mapstructure:"oracledb.system.active_parallel_sessions"`
	OracledbSystemActiveSerialSessions                         MetricConfig `mapstructure:"oracledb.system.active_serial_sessions"`
	OracledbSystemAverageActiveSessions                        MetricConfig `mapstructure:"oracledb.system.average_active_sessions"`
	OracledbSystemBackgroundCheckpointsPerSecond               MetricConfig `mapstructure:"oracledb.system.background_checkpoints_per_second"`
	OracledbSystemBackgroundCPUUsagePerSecond                  MetricConfig `mapstructure:"oracledb.system.background_cpu_usage_per_second"`
	OracledbSystemBackgroundTimePerSecond                      MetricConfig `mapstructure:"oracledb.system.background_time_per_second"`
	OracledbSystemBranchNodeSplitsPerSecond                    MetricConfig `mapstructure:"oracledb.system.branch_node_splits_per_second"`
	OracledbSystemBranchNodeSplitsPerTransaction               MetricConfig `mapstructure:"oracledb.system.branch_node_splits_per_transaction"`
	OracledbSystemBufferCacheHitRatio                          MetricConfig `mapstructure:"oracledb.system.buffer_cache_hit_ratio"`
	OracledbSystemCapturedUserCalls                            MetricConfig `mapstructure:"oracledb.system.captured_user_calls"`
	OracledbSystemConsistentReadChangesPerSecond               MetricConfig `mapstructure:"oracledb.system.consistent_read_changes_per_second"`
	OracledbSystemConsistentReadChangesPerTransaction          MetricConfig `mapstructure:"oracledb.system.consistent_read_changes_per_transaction"`
	OracledbSystemConsistentReadGetsPerSecond                  MetricConfig `mapstructure:"oracledb.system.consistent_read_gets_per_second"`
	OracledbSystemConsistentReadGetsPerTransaction             MetricConfig `mapstructure:"oracledb.system.consistent_read_gets_per_transaction"`
	OracledbSystemCPUUsagePerSecond                            MetricConfig `mapstructure:"oracledb.system.cpu_usage_per_second"`
	OracledbSystemCPUUsagePerTransaction                       MetricConfig `mapstructure:"oracledb.system.cpu_usage_per_transaction"`
	OracledbSystemCrBlocksCreatedPerSecond                     MetricConfig `mapstructure:"oracledb.system.cr_blocks_created_per_second"`
	OracledbSystemCrBlocksCreatedPerTransaction                MetricConfig `mapstructure:"oracledb.system.cr_blocks_created_per_transaction"`
	OracledbSystemCrUndoRecordsAppliedPerSecond                MetricConfig `mapstructure:"oracledb.system.cr_undo_records_applied_per_second"`
	OracledbSystemCrUndoRecordsAppliedPerTransaction           MetricConfig `mapstructure:"oracledb.system.cr_undo_records_applied_per_transaction"`
	OracledbSystemCurrentLogonsCount                           MetricConfig `mapstructure:"oracledb.system.current_logons_count"`
	OracledbSystemCurrentOpenCursorsCount                      MetricConfig `mapstructure:"oracledb.system.current_open_cursors_count"`
	OracledbSystemCurrentOsLoad                                MetricConfig `mapstructure:"oracledb.system.current_os_load"`
	OracledbSystemCursorCacheHitRatio                          MetricConfig `mapstructure:"oracledb.system.cursor_cache_hit_ratio"`
	OracledbSystemDatabaseCPUTimeRatio                         MetricConfig `mapstructure:"oracledb.system.database_cpu_time_ratio"`
	OracledbSystemDatabaseTimePerSecond                        MetricConfig `mapstructure:"oracledb.system.database_time_per_second"`
	OracledbSystemDatabaseWaitTimeRatio                        MetricConfig `mapstructure:"oracledb.system.database_wait_time_ratio"`
	OracledbSystemDbBlockChangesPerSecond                      MetricConfig `mapstructure:"oracledb.system.db_block_changes_per_second"`
	OracledbSystemDbBlockChangesPerTransaction                 MetricConfig `mapstructure:"oracledb.system.db_block_changes_per_transaction"`
	OracledbSystemDbBlockChangesPerUserCall                    MetricConfig `mapstructure:"oracledb.system.db_block_changes_per_user_call"`
	OracledbSystemDbBlockGetsPerSecond                         MetricConfig `mapstructure:"oracledb.system.db_block_gets_per_second"`
	OracledbSystemDbBlockGetsPerTransaction                    MetricConfig `mapstructure:"oracledb.system.db_block_gets_per_transaction"`
	OracledbSystemDbBlockGetsPerUserCall                       MetricConfig `mapstructure:"oracledb.system.db_block_gets_per_user_call"`
	OracledbSystemDbwrCheckpointsPerSecond                     MetricConfig `mapstructure:"oracledb.system.dbwr_checkpoints_per_second"`
	OracledbSystemDiskSortPerSecond                            MetricConfig `mapstructure:"oracledb.system.disk_sort_per_second"`
	OracledbSystemDiskSortPerTransaction                       MetricConfig `mapstructure:"oracledb.system.disk_sort_per_transaction"`
	OracledbSystemEnqueueDeadlocksPerSecond                    MetricConfig `mapstructure:"oracledb.system.enqueue_deadlocks_per_second"`
	OracledbSystemEnqueueDeadlocksPerTransaction               MetricConfig `mapstructure:"oracledb.system.enqueue_deadlocks_per_transaction"`
	OracledbSystemEnqueueRequestsPerSecond                     MetricConfig `mapstructure:"oracledb.system.enqueue_requests_per_second"`
	OracledbSystemEnqueueRequestsPerTransaction                MetricConfig `mapstructure:"oracledb.system.enqueue_requests_per_transaction"`
	OracledbSystemEnqueueTimeoutsPerSecond                     MetricConfig `mapstructure:"oracledb.system.enqueue_timeouts_per_second"`
	OracledbSystemEnqueueTimeoutsPerTransaction                MetricConfig `mapstructure:"oracledb.system.enqueue_timeouts_per_transaction"`
	OracledbSystemEnqueueWaitsPerSecond                        MetricConfig `mapstructure:"oracledb.system.enqueue_waits_per_second"`
	OracledbSystemEnqueueWaitsPerTransaction                   MetricConfig `mapstructure:"oracledb.system.enqueue_waits_per_transaction"`
	OracledbSystemExecuteWithoutParseRatio                     MetricConfig `mapstructure:"oracledb.system.execute_without_parse_ratio"`
	OracledbSystemExecutionsPerSecond                          MetricConfig `mapstructure:"oracledb.system.executions_per_second"`
	OracledbSystemExecutionsPerTransaction                     MetricConfig `mapstructure:"oracledb.system.executions_per_transaction"`
	OracledbSystemExecutionsPerUserCall                        MetricConfig `mapstructure:"oracledb.system.executions_per_user_call"`
	OracledbSystemFullIndexScansPerSecond                      MetricConfig `mapstructure:"oracledb.system.full_index_scans_per_second"`
	OracledbSystemFullIndexScansPerTransaction                 MetricConfig `mapstructure:"oracledb.system.full_index_scans_per_transaction"`
	OracledbSystemGcCrBlockReceivedPerSecond                   MetricConfig `mapstructure:"oracledb.system.gc_cr_block_received_per_second"`
	OracledbSystemGcCrBlockReceivedPerTransaction              MetricConfig `mapstructure:"oracledb.system.gc_cr_block_received_per_transaction"`
	OracledbSystemGcCurrentBlockReceivedPerSecond              MetricConfig `mapstructure:"oracledb.system.gc_current_block_received_per_second"`
	OracledbSystemGcCurrentBlockReceivedPerTransaction         MetricConfig `mapstructure:"oracledb.system.gc_current_block_received_per_transaction"`
	OracledbSystemGlobalCacheAverageCrGetTime                  MetricConfig `mapstructure:"oracledb.system.global_cache_average_cr_get_time"`
	OracledbSystemGlobalCacheAverageCurrentGetTime             MetricConfig `mapstructure:"oracledb.system.global_cache_average_current_get_time"`
	OracledbSystemGlobalCacheBlocksCorrupted                   MetricConfig `mapstructure:"oracledb.system.global_cache_blocks_corrupted"`
	OracledbSystemGlobalCacheBlocksLost                        MetricConfig `mapstructure:"oracledb.system.global_cache_blocks_lost"`
	OracledbSystemHardParseCountPerSecond                      MetricConfig `mapstructure:"oracledb.system.hard_parse_count_per_second"`
	OracledbSystemHardParseCountPerTransaction                 MetricConfig `mapstructure:"oracledb.system.hard_parse_count_per_transaction"`
	OracledbSystemHostCPUUsagePerSecond                        MetricConfig `mapstructure:"oracledb.system.host_cpu_usage_per_second"`
	OracledbSystemHostCPUUtilization                           MetricConfig `mapstructure:"oracledb.system.host_cpu_utilization"`
	OracledbSystemIoMegabytesPerSecond                         MetricConfig `mapstructure:"oracledb.system.io_megabytes_per_second"`
	OracledbSystemIoRequestsPerSecond                          MetricConfig `mapstructure:"oracledb.system.io_requests_per_second"`
	OracledbSystemLeafNodeSplitsPerSecond                      MetricConfig `mapstructure:"oracledb.system.leaf_node_splits_per_second"`
	OracledbSystemLeafNodeSplitsPerTransaction                 MetricConfig `mapstructure:"oracledb.system.leaf_node_splits_per_transaction"`
	OracledbSystemLibraryCacheHitRatio                         MetricConfig `mapstructure:"oracledb.system.library_cache_hit_ratio"`
	OracledbSystemLibraryCacheMissRatio                        MetricConfig `mapstructure:"oracledb.system.library_cache_miss_ratio"`
	OracledbSystemLogicalReadsPerSecond                        MetricConfig `mapstructure:"oracledb.system.logical_reads_per_second"`
	OracledbSystemLogicalReadsPerTransaction                   MetricConfig `mapstructure:"oracledb.system.logical_reads_per_transaction"`
	OracledbSystemLogicalReadsPerUserCall                      MetricConfig `mapstructure:"oracledb.system.logical_reads_per_user_call"`
	OracledbSystemLogonsPerSecond                              MetricConfig `mapstructure:"oracledb.system.logons_per_second"`
	OracledbSystemLogonsPerTransaction                         MetricConfig `mapstructure:"oracledb.system.logons_per_transaction"`
	OracledbSystemLongTableScansPerSecond                      MetricConfig `mapstructure:"oracledb.system.long_table_scans_per_second"`
	OracledbSystemLongTableScansPerTransaction                 MetricConfig `mapstructure:"oracledb.system.long_table_scans_per_transaction"`
	OracledbSystemMemorySortsRatio                             MetricConfig `mapstructure:"oracledb.system.memory_sorts_ratio"`
	OracledbSystemNetworkTrafficVolumePerSecond                MetricConfig `mapstructure:"oracledb.system.network_traffic_volume_per_second"`
	OracledbSystemOpenCursorsPerSecond                         MetricConfig `mapstructure:"oracledb.system.open_cursors_per_second"`
	OracledbSystemOpenCursorsPerTransaction                    MetricConfig `mapstructure:"oracledb.system.open_cursors_per_transaction"`
	OracledbSystemParseFailureCountPerSecond                   MetricConfig `mapstructure:"oracledb.system.parse_failure_count_per_second"`
	OracledbSystemParseFailureCountPerTransaction              MetricConfig `mapstructure:"oracledb.system.parse_failure_count_per_transaction"`
	OracledbSystemPgaCacheHitPercentage                        MetricConfig `mapstructure:"oracledb.system.pga_cache_hit_percentage"`
	OracledbSystemPhysicalLobsReadsPerSecond                   MetricConfig `mapstructure:"oracledb.system.physical_lobs_reads_per_second"`
	OracledbSystemPhysicalLobsReadsPerTransaction              MetricConfig `mapstructure:"oracledb.system.physical_lobs_reads_per_transaction"`
	OracledbSystemPhysicalLobsWritesPerSecond                  MetricConfig `mapstructure:"oracledb.system.physical_lobs_writes_per_second"`
	OracledbSystemPhysicalLobsWritesPerTransaction             MetricConfig `mapstructure:"oracledb.system.physical_lobs_writes_per_transaction"`
	OracledbSystemPhysicalReadBytesPerSecond                   MetricConfig `mapstructure:"oracledb.system.physical_read_bytes_per_second"`
	OracledbSystemPhysicalReadIoRequestsPerSecond              MetricConfig `mapstructure:"oracledb.system.physical_read_io_requests_per_second"`
	OracledbSystemPhysicalReadTotalBytesPerSecond              MetricConfig `mapstructure:"oracledb.system.physical_read_total_bytes_per_second"`
	OracledbSystemPhysicalReadTotalIoRequestsPerSecond         MetricConfig `mapstructure:"oracledb.system.physical_read_total_io_requests_per_second"`
	OracledbSystemPhysicalReadsDirectPerSecond                 MetricConfig `mapstructure:"oracledb.system.physical_reads_direct_per_second"`
	OracledbSystemPhysicalReadsDirectPerTransaction            MetricConfig `mapstructure:"oracledb.system.physical_reads_direct_per_transaction"`
	OracledbSystemPhysicalReadsPerSecond                       MetricConfig `mapstructure:"oracledb.system.physical_reads_per_second"`
	OracledbSystemPhysicalReadsPerTransaction                  MetricConfig `mapstructure:"oracledb.system.physical_reads_per_transaction"`
	OracledbSystemPhysicalWriteBytesPerSecond                  MetricConfig `mapstructure:"oracledb.system.physical_write_bytes_per_second"`
	OracledbSystemPhysicalWriteIoRequestsPerSecond             MetricConfig `mapstructure:"oracledb.system.physical_write_io_requests_per_second"`
	OracledbSystemPhysicalWriteTotalBytesPerSecond             MetricConfig `mapstructure:"oracledb.system.physical_write_total_bytes_per_second"`
	OracledbSystemPhysicalWriteTotalIoRequestsPerSecond        MetricConfig `mapstructure:"oracledb.system.physical_write_total_io_requests_per_second"`
	OracledbSystemPhysicalWritesDirectPerSecond                MetricConfig `mapstructure:"oracledb.system.physical_writes_direct_per_second"`
	OracledbSystemPhysicalWritesDirectPerTransaction           MetricConfig `mapstructure:"oracledb.system.physical_writes_direct_per_transaction"`
	OracledbSystemPhysicalWritesPerSecond                      MetricConfig `mapstructure:"oracledb.system.physical_writes_per_second"`
	OracledbSystemPhysicalWritesPerTransaction                 MetricConfig `mapstructure:"oracledb.system.physical_writes_per_transaction"`
	OracledbSystemProcessLimitPercentage                       MetricConfig `mapstructure:"oracledb.system.process_limit_percentage"`
	OracledbSystemRecursiveCallsPerSecond                      MetricConfig `mapstructure:"oracledb.system.recursive_calls_per_second"`
	OracledbSystemRecursiveCallsPerTransaction                 MetricConfig `mapstructure:"oracledb.system.recursive_calls_per_transaction"`
	OracledbSystemRedoAllocationHitRatio                       MetricConfig `mapstructure:"oracledb.system.redo_allocation_hit_ratio"`
	OracledbSystemRedoGeneratedBytesPerSecond                  MetricConfig `mapstructure:"oracledb.system.redo_generated_bytes_per_second"`
	OracledbSystemRedoGeneratedBytesPerTransaction             MetricConfig `mapstructure:"oracledb.system.redo_generated_bytes_per_transaction"`
	OracledbSystemRedoWritesPerSecond                          MetricConfig `mapstructure:"oracledb.system.redo_writes_per_second"`
	OracledbSystemRedoWritesPerTransaction                     MetricConfig `mapstructure:"oracledb.system.redo_writes_per_transaction"`
	OracledbSystemResponseTimePerTransaction                   MetricConfig `mapstructure:"oracledb.system.response_time_per_transaction"`
	OracledbSystemRowCacheHitRatio                             MetricConfig `mapstructure:"oracledb.system.row_cache_hit_ratio"`
	OracledbSystemRowCacheMissRatio                            MetricConfig `mapstructure:"oracledb.system.row_cache_miss_ratio"`
	OracledbSystemRowsPerSort                                  MetricConfig `mapstructure:"oracledb.system.rows_per_sort"`
	OracledbSystemSessionCount                                 MetricConfig `mapstructure:"oracledb.system.session_count"`
	OracledbSystemSessionLimitPercentage                       MetricConfig `mapstructure:"oracledb.system.session_limit_percentage"`
	OracledbSystemSharedPoolFreePercentage                     MetricConfig `mapstructure:"oracledb.system.shared_pool_free_percentage"`
	OracledbSystemSoftParseRatio                               MetricConfig `mapstructure:"oracledb.system.soft_parse_ratio"`
	OracledbSystemSQLServiceResponseTime                       MetricConfig `mapstructure:"oracledb.system.sql_service_response_time"`
	OracledbSystemStreamsPoolUsagePercentage                   MetricConfig `mapstructure:"oracledb.system.streams_pool_usage_percentage"`
	OracledbSystemTempSpaceUsed                                MetricConfig `mapstructure:"oracledb.system.temp_space_used"`
	OracledbSystemTotalIndexScansPerSecond                     MetricConfig `mapstructure:"oracledb.system.total_index_scans_per_second"`
	OracledbSystemTotalIndexScansPerTransaction                MetricConfig `mapstructure:"oracledb.system.total_index_scans_per_transaction"`
	OracledbSystemTotalParseCountPerSecond                     MetricConfig `mapstructure:"oracledb.system.total_parse_count_per_second"`
	OracledbSystemTotalParseCountPerTransaction                MetricConfig `mapstructure:"oracledb.system.total_parse_count_per_transaction"`
	OracledbSystemTotalSortsPerUserCall                        MetricConfig `mapstructure:"oracledb.system.total_sorts_per_user_call"`
	OracledbSystemTotalTableScansPerSecond                     MetricConfig `mapstructure:"oracledb.system.total_table_scans_per_second"`
	OracledbSystemTotalTableScansPerTransaction                MetricConfig `mapstructure:"oracledb.system.total_table_scans_per_transaction"`
	OracledbSystemTotalTableScansPerUserCall                   MetricConfig `mapstructure:"oracledb.system.total_table_scans_per_user_call"`
	OracledbSystemTransactionsPerLogon                         MetricConfig `mapstructure:"oracledb.system.transactions_per_logon"`
	OracledbSystemTransactionsPerSecond                        MetricConfig `mapstructure:"oracledb.system.transactions_per_second"`
	OracledbSystemUserCallsPerSecond                           MetricConfig `mapstructure:"oracledb.system.user_calls_per_second"`
	OracledbSystemUserCallsPerTransaction                      MetricConfig `mapstructure:"oracledb.system.user_calls_per_transaction"`
	OracledbSystemUserCallsRatio                               MetricConfig `mapstructure:"oracledb.system.user_calls_ratio"`
	OracledbSystemUserCommitsPerSecond                         MetricConfig `mapstructure:"oracledb.system.user_commits_per_second"`
	OracledbSystemUserCommitsPercentage                        MetricConfig `mapstructure:"oracledb.system.user_commits_percentage"`
	OracledbSystemUserLimitPercentage                          MetricConfig `mapstructure:"oracledb.system.user_limit_percentage"`
	OracledbSystemUserRollbackUndoRecordsAppliedPerSecond      MetricConfig `mapstructure:"oracledb.system.user_rollback_undo_records_applied_per_second"`
	OracledbSystemUserRollbackUndoRecordsAppliedPerTransaction MetricConfig `mapstructure:"oracledb.system.user_rollback_undo_records_applied_per_transaction"`
	OracledbSystemUserRollbacksPerSecond                       MetricConfig `mapstructure:"oracledb.system.user_rollbacks_per_second"`
	OracledbSystemUserRollbacksPercentage                      MetricConfig `mapstructure:"oracledb.system.user_rollbacks_percentage"`
	OracledbTablespaceDbID                                     MetricConfig `mapstructure:"oracledb.tablespace.db_id"`
	OracledbTablespaceGlobalName                               MetricConfig `mapstructure:"oracledb.tablespace.global_name"`
	OracledbTablespaceIsOffline                                MetricConfig `mapstructure:"oracledb.tablespace.is_offline"`
	OracledbTablespaceOfflineCdbDatafiles                      MetricConfig `mapstructure:"oracledb.tablespace.offline_cdb_datafiles"`
	OracledbTablespaceOfflinePdbDatafiles                      MetricConfig `mapstructure:"oracledb.tablespace.offline_pdb_datafiles"`
	OracledbTablespacePdbNonWriteMode                          MetricConfig `mapstructure:"oracledb.tablespace.pdb_non_write_mode"`
	OracledbTablespaceSpaceConsumedBytes                       MetricConfig `mapstructure:"oracledb.tablespace.space_consumed_bytes"`
	OracledbTablespaceSpaceReservedBytes                       MetricConfig `mapstructure:"oracledb.tablespace.space_reserved_bytes"`
	OracledbTablespaceSpaceUsedPercentage                      MetricConfig `mapstructure:"oracledb.tablespace.space_used_percentage"`
	OracledbTablespaceTotalBytes                               MetricConfig `mapstructure:"oracledb.tablespace.total_bytes"`
	OracledbTablespaceUsedBytes                                MetricConfig `mapstructure:"oracledb.tablespace.used_bytes"`
	OracledbTablespaceUsedPercent                              MetricConfig `mapstructure:"oracledb.tablespace.used_percent"`
	OracledbWaitEventsCurrentWaitTimeMs                        MetricConfig `mapstructure:"oracledb.wait_events.current_wait_time_ms"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		OracledbAsmDiskgroupFreeMb: MetricConfig{
			Enabled: true,
		},
		OracledbAsmDiskgroupOfflineDisks: MetricConfig{
			Enabled: true,
		},
		OracledbAsmDiskgroupTotalMb: MetricConfig{
			Enabled: true,
		},
		OracledbChildCursorsBufferGets: MetricConfig{
			Enabled: true,
		},
		OracledbChildCursorsCPUTime: MetricConfig{
			Enabled: true,
		},
		OracledbChildCursorsDetails: MetricConfig{
			Enabled: true,
		},
		OracledbChildCursorsDiskReads: MetricConfig{
			Enabled: true,
		},
		OracledbChildCursorsElapsedTime: MetricConfig{
			Enabled: true,
		},
		OracledbChildCursorsExecutions: MetricConfig{
			Enabled: true,
		},
		OracledbChildCursorsInvalidations: MetricConfig{
			Enabled: true,
		},
		OracledbChildCursorsUserIoWaitTime: MetricConfig{
			Enabled: true,
		},
		OracledbConnectionActiveSessions: MetricConfig{
			Enabled: true,
		},
		OracledbConnectionBytesReceived: MetricConfig{
			Enabled: true,
		},
		OracledbConnectionBytesSent: MetricConfig{
			Enabled: true,
		},
		OracledbConnectionCircuits: MetricConfig{
			Enabled: true,
		},
		OracledbConnectionDispatchers: MetricConfig{
			Enabled: true,
		},
		OracledbConnectionExecuteCount: MetricConfig{
			Enabled: true,
		},
		OracledbConnectionInactiveSessions: MetricConfig{
			Enabled: true,
		},
		OracledbConnectionLogonsCumulative: MetricConfig{
			Enabled: true,
		},
		OracledbConnectionLogonsCurrent: MetricConfig{
			Enabled: true,
		},
		OracledbConnectionParseCountHard: MetricConfig{
			Enabled: true,
		},
		OracledbConnectionParseCountTotal: MetricConfig{
			Enabled: true,
		},
		OracledbConnectionResourceCurrentUtilization: MetricConfig{
			Enabled: true,
		},
		OracledbConnectionResourceLimit: MetricConfig{
			Enabled: true,
		},
		OracledbConnectionResourceMaxUtilization: MetricConfig{
			Enabled: true,
		},
		OracledbConnectionSessionsByStatus: MetricConfig{
			Enabled: true,
		},
		OracledbConnectionSessionsByType: MetricConfig{
			Enabled: true,
		},
		OracledbConnectionSharedServers: MetricConfig{
			Enabled: true,
		},
		OracledbConnectionSqlnetRoundtrips: MetricConfig{
			Enabled: true,
		},
		OracledbConnectionTotalSessions: MetricConfig{
			Enabled: true,
		},
		OracledbConnectionUserCommits: MetricConfig{
			Enabled: true,
		},
		OracledbConnectionUserRollbacks: MetricConfig{
			Enabled: true,
		},
		OracledbContainerRestricted: MetricConfig{
			Enabled: true,
		},
		OracledbContainerStatus: MetricConfig{
			Enabled: true,
		},
		OracledbDatabaseInfo: MetricConfig{
			Enabled: true,
		},
		OracledbDatabaseRole: MetricConfig{
			Enabled: true,
		},
		OracledbDatafileAutoextensible: MetricConfig{
			Enabled: true,
		},
		OracledbDatafileSizeBytes: MetricConfig{
			Enabled: true,
		},
		OracledbDatafileUsedBytes: MetricConfig{
			Enabled: true,
		},
		OracledbDbID: MetricConfig{
			Enabled: true,
		},
		OracledbDiskBlocksRead: MetricConfig{
			Enabled: true,
		},
		OracledbDiskBlocksWritten: MetricConfig{
			Enabled: true,
		},
		OracledbDiskReadTimeMilliseconds: MetricConfig{
			Enabled: true,
		},
		OracledbDiskReads: MetricConfig{
			Enabled: true,
		},
		OracledbDiskWriteTimeMilliseconds: MetricConfig{
			Enabled: true,
		},
		OracledbDiskWrites: MetricConfig{
			Enabled: true,
		},
		OracledbExecutionPlan: MetricConfig{
			Enabled: true,
		},
		OracledbGlobalName: MetricConfig{
			Enabled: true,
		},
		OracledbHostingInfo: MetricConfig{
			Enabled: true,
		},
		OracledbLockedAccounts: MetricConfig{
			Enabled: true,
		},
		OracledbLongRunningQueries: MetricConfig{
			Enabled: true,
		},
		OracledbMemoryPgaAllocatedBytes: MetricConfig{
			Enabled: true,
		},
		OracledbMemoryPgaFreeableBytes: MetricConfig{
			Enabled: true,
		},
		OracledbMemoryPgaInUseBytes: MetricConfig{
			Enabled: true,
		},
		OracledbMemoryPgaMaxSizeBytes: MetricConfig{
			Enabled: true,
		},
		OracledbMemorySgaSharedPoolLibraryCacheSharableBytes: MetricConfig{
			Enabled: true,
		},
		OracledbMemorySgaSharedPoolLibraryCacheUserBytes: MetricConfig{
			Enabled: true,
		},
		OracledbMemorySgaUgaTotalBytes: MetricConfig{
			Enabled: true,
		},
		OracledbPdbActiveParallelSessions: MetricConfig{
			Enabled: true,
		},
		OracledbPdbActiveSerialSessions: MetricConfig{
			Enabled: true,
		},
		OracledbPdbAverageActiveSessions: MetricConfig{
			Enabled: true,
		},
		OracledbPdbBackgroundCPUUsagePerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbPdbBackgroundTimePerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbPdbBlockChangesPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbPdbBlockChangesPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbPdbCPUTimeRatio: MetricConfig{
			Enabled: true,
		},
		OracledbPdbCPUUsagePerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbPdbCPUUsagePerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbPdbCurrentLogons: MetricConfig{
			Enabled: true,
		},
		OracledbPdbCurrentOpenCursors: MetricConfig{
			Enabled: true,
		},
		OracledbPdbDbPhysicalReadBytesPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbPdbDbPhysicalReadsPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbPdbDbPhysicalWriteBytesPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbPdbDbPhysicalWritesPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbPdbExecuteWithoutParseRatio: MetricConfig{
			Enabled: true,
		},
		OracledbPdbExecutionsPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbPdbExecutionsPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbPdbHardParseCountPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbPdbHardParseCountPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbPdbLogicalReadsPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbPdbLogicalReadsPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbPdbLogonsPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbPdbLogonsPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbPdbNetworkTrafficBytePerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbPdbOpenCursorsPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbPdbOpenCursorsPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbPdbOpenMode: MetricConfig{
			Enabled: true,
		},
		OracledbPdbParseFailureCountPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbPdbPhysicalReadBytesPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbPdbPhysicalReadsPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbPdbPhysicalWriteBytesPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbPdbPhysicalWritesPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbPdbRedoGeneratedBytesPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbPdbRedoGeneratedBytesPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbPdbResponseTimePerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbPdbSessionCount: MetricConfig{
			Enabled: true,
		},
		OracledbPdbSoftParseRatio: MetricConfig{
			Enabled: true,
		},
		OracledbPdbSQLServiceResponseTime: MetricConfig{
			Enabled: true,
		},
		OracledbPdbTotalParseCountPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbPdbTotalParseCountPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbPdbTotalSizeBytes: MetricConfig{
			Enabled: true,
		},
		OracledbPdbTransactionsPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbPdbUserCallsPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbPdbUserCallsPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbPdbUserCommitsPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbPdbUserCommitsPercentage: MetricConfig{
			Enabled: true,
		},
		OracledbPdbUserRollbacksPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbPdbUserRollbacksPercentage: MetricConfig{
			Enabled: true,
		},
		OracledbPdbWaitTimeRatio: MetricConfig{
			Enabled: true,
		},
		OracledbRacInstanceActiveState: MetricConfig{
			Enabled: true,
		},
		OracledbRacInstanceArchiverStarted: MetricConfig{
			Enabled: true,
		},
		OracledbRacInstanceDatabaseStatus: MetricConfig{
			Enabled: true,
		},
		OracledbRacInstanceLoginsAllowed: MetricConfig{
			Enabled: true,
		},
		OracledbRacInstanceStatus: MetricConfig{
			Enabled: true,
		},
		OracledbRacInstanceUptimeSeconds: MetricConfig{
			Enabled: true,
		},
		OracledbRacInstanceVersionInfo: MetricConfig{
			Enabled: true,
		},
		OracledbRacServiceBlockedStatus: MetricConfig{
			Enabled: true,
		},
		OracledbRacServiceClbConfig: MetricConfig{
			Enabled: true,
		},
		OracledbRacServiceDrainTimeoutSeconds: MetricConfig{
			Enabled: true,
		},
		OracledbRacServiceFanEnabled: MetricConfig{
			Enabled: true,
		},
		OracledbRacServiceGoalConfig: MetricConfig{
			Enabled: true,
		},
		OracledbRacServiceInstanceID: MetricConfig{
			Enabled: true,
		},
		OracledbRacServiceNetworkConfig: MetricConfig{
			Enabled: true,
		},
		OracledbRacServiceReplayTimeoutSeconds: MetricConfig{
			Enabled: true,
		},
		OracledbRacServiceTransactionGuardEnabled: MetricConfig{
			Enabled: true,
		},
		OracledbRacTotalWaits: MetricConfig{
			Enabled: true,
		},
		OracledbRacWaitTime: MetricConfig{
			Enabled: true,
		},
		OracledbRedoLogParallelWriteWaits: MetricConfig{
			Enabled: true,
		},
		OracledbRedoLogSwitchArchivingNeededWaits: MetricConfig{
			Enabled: true,
		},
		OracledbRedoLogSwitchCheckpointIncompleteWaits: MetricConfig{
			Enabled: true,
		},
		OracledbRedoLogSwitchCompletionWaits: MetricConfig{
			Enabled: true,
		},
		OracledbRollbackSegmentsGets: MetricConfig{
			Enabled: true,
		},
		OracledbRollbackSegmentsWaitRatio: MetricConfig{
			Enabled: true,
		},
		OracledbRollbackSegmentsWaits: MetricConfig{
			Enabled: true,
		},
		OracledbServiceCount: MetricConfig{
			Enabled: true,
		},
		OracledbServiceStatus: MetricConfig{
			Enabled: true,
		},
		OracledbSessionsCount: MetricConfig{
			Enabled: true,
		},
		OracledbSgaBufferBusyWaits: MetricConfig{
			Enabled: true,
		},
		OracledbSgaFixedSizeBytes: MetricConfig{
			Enabled: true,
		},
		OracledbSgaFreeBufferInspectedWaits: MetricConfig{
			Enabled: true,
		},
		OracledbSgaFreeBufferWaits: MetricConfig{
			Enabled: true,
		},
		OracledbSgaHitRatio: MetricConfig{
			Enabled: true,
		},
		OracledbSgaLogAllocationRetriesRatio: MetricConfig{
			Enabled: true,
		},
		OracledbSgaLogBufferRedoAllocationRetries: MetricConfig{
			Enabled: true,
		},
		OracledbSgaLogBufferRedoEntries: MetricConfig{
			Enabled: true,
		},
		OracledbSgaLogBufferSpaceWaits: MetricConfig{
			Enabled: true,
		},
		OracledbSgaRedoBuffersBytes: MetricConfig{
			Enabled: true,
		},
		OracledbSgaSharedPoolDictCacheMissRatio: MetricConfig{
			Enabled: true,
		},
		OracledbSgaSharedPoolLibraryCacheHitRatio: MetricConfig{
			Enabled: true,
		},
		OracledbSgaSharedPoolLibraryCacheReloadRatio: MetricConfig{
			Enabled: true,
		},
		OracledbSlowQueriesExecutionCount: MetricConfig{
			Enabled: true,
		},
		OracledbSlowQueriesIntervalAvgBufferGets: MetricConfig{
			Enabled: true,
		},
		OracledbSlowQueriesIntervalAvgCPUTime: MetricConfig{
			Enabled: true,
		},
		OracledbSlowQueriesIntervalAvgDiskReads: MetricConfig{
			Enabled: true,
		},
		OracledbSlowQueriesIntervalAvgDiskWrites: MetricConfig{
			Enabled: true,
		},
		OracledbSlowQueriesIntervalAvgElapsedTime: MetricConfig{
			Enabled: true,
		},
		OracledbSlowQueriesIntervalAvgRowsProcessed: MetricConfig{
			Enabled: true,
		},
		OracledbSlowQueriesIntervalAvgWaitTime: MetricConfig{
			Enabled: true,
		},
		OracledbSlowQueriesIntervalBufferGets: MetricConfig{
			Enabled: true,
		},
		OracledbSlowQueriesIntervalCPUTime: MetricConfig{
			Enabled: true,
		},
		OracledbSlowQueriesIntervalDiskReads: MetricConfig{
			Enabled: true,
		},
		OracledbSlowQueriesIntervalDiskWrites: MetricConfig{
			Enabled: true,
		},
		OracledbSlowQueriesIntervalElapsedTime: MetricConfig{
			Enabled: true,
		},
		OracledbSlowQueriesIntervalExecutionCount: MetricConfig{
			Enabled: true,
		},
		OracledbSlowQueriesIntervalRowsProcessed: MetricConfig{
			Enabled: true,
		},
		OracledbSlowQueriesIntervalWaitTime: MetricConfig{
			Enabled: true,
		},
		OracledbSlowQueriesQueryDetails: MetricConfig{
			Enabled: true,
		},
		OracledbSlowQueriesTotalCPUTime: MetricConfig{
			Enabled: true,
		},
		OracledbSlowQueriesTotalDiskReads: MetricConfig{
			Enabled: true,
		},
		OracledbSlowQueriesTotalDiskWrites: MetricConfig{
			Enabled: true,
		},
		OracledbSlowQueriesTotalElapsedTime: MetricConfig{
			Enabled: true,
		},
		OracledbSlowQueriesTotalRowsExamined: MetricConfig{
			Enabled: true,
		},
		OracledbSlowQueriesTotalRowsReturned: MetricConfig{
			Enabled: true,
		},
		OracledbSlowQueriesTotalWaitTime: MetricConfig{
			Enabled: true,
		},
		OracledbSortsDisk: MetricConfig{
			Enabled: true,
		},
		OracledbSortsMemory: MetricConfig{
			Enabled: true,
		},
		OracledbSystemActiveParallelSessions: MetricConfig{
			Enabled: true,
		},
		OracledbSystemActiveSerialSessions: MetricConfig{
			Enabled: true,
		},
		OracledbSystemAverageActiveSessions: MetricConfig{
			Enabled: true,
		},
		OracledbSystemBackgroundCheckpointsPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemBackgroundCPUUsagePerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemBackgroundTimePerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemBranchNodeSplitsPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemBranchNodeSplitsPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemBufferCacheHitRatio: MetricConfig{
			Enabled: true,
		},
		OracledbSystemCapturedUserCalls: MetricConfig{
			Enabled: true,
		},
		OracledbSystemConsistentReadChangesPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemConsistentReadChangesPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemConsistentReadGetsPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemConsistentReadGetsPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemCPUUsagePerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemCPUUsagePerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemCrBlocksCreatedPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemCrBlocksCreatedPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemCrUndoRecordsAppliedPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemCrUndoRecordsAppliedPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemCurrentLogonsCount: MetricConfig{
			Enabled: true,
		},
		OracledbSystemCurrentOpenCursorsCount: MetricConfig{
			Enabled: true,
		},
		OracledbSystemCurrentOsLoad: MetricConfig{
			Enabled: true,
		},
		OracledbSystemCursorCacheHitRatio: MetricConfig{
			Enabled: true,
		},
		OracledbSystemDatabaseCPUTimeRatio: MetricConfig{
			Enabled: true,
		},
		OracledbSystemDatabaseTimePerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemDatabaseWaitTimeRatio: MetricConfig{
			Enabled: true,
		},
		OracledbSystemDbBlockChangesPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemDbBlockChangesPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemDbBlockChangesPerUserCall: MetricConfig{
			Enabled: true,
		},
		OracledbSystemDbBlockGetsPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemDbBlockGetsPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemDbBlockGetsPerUserCall: MetricConfig{
			Enabled: true,
		},
		OracledbSystemDbwrCheckpointsPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemDiskSortPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemDiskSortPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemEnqueueDeadlocksPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemEnqueueDeadlocksPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemEnqueueRequestsPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemEnqueueRequestsPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemEnqueueTimeoutsPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemEnqueueTimeoutsPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemEnqueueWaitsPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemEnqueueWaitsPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemExecuteWithoutParseRatio: MetricConfig{
			Enabled: true,
		},
		OracledbSystemExecutionsPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemExecutionsPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemExecutionsPerUserCall: MetricConfig{
			Enabled: true,
		},
		OracledbSystemFullIndexScansPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemFullIndexScansPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemGcCrBlockReceivedPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemGcCrBlockReceivedPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemGcCurrentBlockReceivedPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemGcCurrentBlockReceivedPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemGlobalCacheAverageCrGetTime: MetricConfig{
			Enabled: true,
		},
		OracledbSystemGlobalCacheAverageCurrentGetTime: MetricConfig{
			Enabled: true,
		},
		OracledbSystemGlobalCacheBlocksCorrupted: MetricConfig{
			Enabled: true,
		},
		OracledbSystemGlobalCacheBlocksLost: MetricConfig{
			Enabled: true,
		},
		OracledbSystemHardParseCountPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemHardParseCountPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemHostCPUUsagePerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemHostCPUUtilization: MetricConfig{
			Enabled: true,
		},
		OracledbSystemIoMegabytesPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemIoRequestsPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemLeafNodeSplitsPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemLeafNodeSplitsPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemLibraryCacheHitRatio: MetricConfig{
			Enabled: true,
		},
		OracledbSystemLibraryCacheMissRatio: MetricConfig{
			Enabled: true,
		},
		OracledbSystemLogicalReadsPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemLogicalReadsPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemLogicalReadsPerUserCall: MetricConfig{
			Enabled: true,
		},
		OracledbSystemLogonsPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemLogonsPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemLongTableScansPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemLongTableScansPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemMemorySortsRatio: MetricConfig{
			Enabled: true,
		},
		OracledbSystemNetworkTrafficVolumePerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemOpenCursorsPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemOpenCursorsPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemParseFailureCountPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemParseFailureCountPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemPgaCacheHitPercentage: MetricConfig{
			Enabled: true,
		},
		OracledbSystemPhysicalLobsReadsPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemPhysicalLobsReadsPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemPhysicalLobsWritesPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemPhysicalLobsWritesPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemPhysicalReadBytesPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemPhysicalReadIoRequestsPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemPhysicalReadTotalBytesPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemPhysicalReadTotalIoRequestsPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemPhysicalReadsDirectPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemPhysicalReadsDirectPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemPhysicalReadsPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemPhysicalReadsPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemPhysicalWriteBytesPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemPhysicalWriteIoRequestsPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemPhysicalWriteTotalBytesPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemPhysicalWriteTotalIoRequestsPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemPhysicalWritesDirectPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemPhysicalWritesDirectPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemPhysicalWritesPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemPhysicalWritesPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemProcessLimitPercentage: MetricConfig{
			Enabled: true,
		},
		OracledbSystemRecursiveCallsPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemRecursiveCallsPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemRedoAllocationHitRatio: MetricConfig{
			Enabled: true,
		},
		OracledbSystemRedoGeneratedBytesPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemRedoGeneratedBytesPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemRedoWritesPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemRedoWritesPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemResponseTimePerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemRowCacheHitRatio: MetricConfig{
			Enabled: true,
		},
		OracledbSystemRowCacheMissRatio: MetricConfig{
			Enabled: true,
		},
		OracledbSystemRowsPerSort: MetricConfig{
			Enabled: true,
		},
		OracledbSystemSessionCount: MetricConfig{
			Enabled: true,
		},
		OracledbSystemSessionLimitPercentage: MetricConfig{
			Enabled: true,
		},
		OracledbSystemSharedPoolFreePercentage: MetricConfig{
			Enabled: true,
		},
		OracledbSystemSoftParseRatio: MetricConfig{
			Enabled: true,
		},
		OracledbSystemSQLServiceResponseTime: MetricConfig{
			Enabled: true,
		},
		OracledbSystemStreamsPoolUsagePercentage: MetricConfig{
			Enabled: true,
		},
		OracledbSystemTempSpaceUsed: MetricConfig{
			Enabled: true,
		},
		OracledbSystemTotalIndexScansPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemTotalIndexScansPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemTotalParseCountPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemTotalParseCountPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemTotalSortsPerUserCall: MetricConfig{
			Enabled: true,
		},
		OracledbSystemTotalTableScansPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemTotalTableScansPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemTotalTableScansPerUserCall: MetricConfig{
			Enabled: true,
		},
		OracledbSystemTransactionsPerLogon: MetricConfig{
			Enabled: true,
		},
		OracledbSystemTransactionsPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemUserCallsPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemUserCallsPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemUserCallsRatio: MetricConfig{
			Enabled: true,
		},
		OracledbSystemUserCommitsPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemUserCommitsPercentage: MetricConfig{
			Enabled: true,
		},
		OracledbSystemUserLimitPercentage: MetricConfig{
			Enabled: true,
		},
		OracledbSystemUserRollbackUndoRecordsAppliedPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemUserRollbackUndoRecordsAppliedPerTransaction: MetricConfig{
			Enabled: true,
		},
		OracledbSystemUserRollbacksPerSecond: MetricConfig{
			Enabled: true,
		},
		OracledbSystemUserRollbacksPercentage: MetricConfig{
			Enabled: true,
		},
		OracledbTablespaceDbID: MetricConfig{
			Enabled: true,
		},
		OracledbTablespaceGlobalName: MetricConfig{
			Enabled: true,
		},
		OracledbTablespaceIsOffline: MetricConfig{
			Enabled: true,
		},
		OracledbTablespaceOfflineCdbDatafiles: MetricConfig{
			Enabled: true,
		},
		OracledbTablespaceOfflinePdbDatafiles: MetricConfig{
			Enabled: true,
		},
		OracledbTablespacePdbNonWriteMode: MetricConfig{
			Enabled: true,
		},
		OracledbTablespaceSpaceConsumedBytes: MetricConfig{
			Enabled: true,
		},
		OracledbTablespaceSpaceReservedBytes: MetricConfig{
			Enabled: true,
		},
		OracledbTablespaceSpaceUsedPercentage: MetricConfig{
			Enabled: true,
		},
		OracledbTablespaceTotalBytes: MetricConfig{
			Enabled: true,
		},
		OracledbTablespaceUsedBytes: MetricConfig{
			Enabled: true,
		},
		OracledbTablespaceUsedPercent: MetricConfig{
			Enabled: true,
		},
		OracledbWaitEventsCurrentWaitTimeMs: MetricConfig{
			Enabled: true,
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for oracledb resource attributes.
type ResourceAttributesConfig struct {
	HostAddress ResourceAttributeConfig `mapstructure:"host.address"`
	HostPort    ResourceAttributeConfig `mapstructure:"host.port"`
	ServiceName ResourceAttributeConfig `mapstructure:"service.name"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		HostAddress: ResourceAttributeConfig{
			Enabled: true,
		},
		HostPort: ResourceAttributeConfig{
			Enabled: true,
		},
		ServiceName: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for oracledb metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}
